export type Verse = {
  reference: string;
  text: string;
};

export const VERSES: Verse[] = [
  { reference: "Jeremias 29:11", text: "Porque sou eu que conheço os planos que tenho para vocês, diz o Senhor, planos de fazê-los prosperar e não de lhes causar dano, planos de dar-lhes esperança e um futuro." },
  { reference: "Salmos 23:1", text: "O Senhor é o meu pastor; de nada terei falta." },
  { reference: "Filipenses 4:13", text: "Tudo posso naquele que me fortalece." },
  { reference: "Provérbios 3:5-6", text: "Confie no Senhor de todo o seu coração e não se apoie em seu próprio entendimento; reconheça o Senhor em todos os seus caminhos, e ele endireitará as suas veredas." },
  { reference: "Romanos 8:28", text: "Sabemos que Deus age em todas as coisas para o bem daqueles que o amam, dos que foram chamados de acordo com o seu propósito." },
  { reference: "Isaías 41:10", text: "Por isso não tema, pois estou com você; não tenha medo, pois sou o seu Deus. Eu o fortalecerei e o ajudarei; eu o segurarei com a minha mão direita vitoriosa." },
  { reference: "Mateus 6:33", text: "Busquem, pois, em primeiro lugar o Reino de Deus e a sua justiça, e todas essas coisas lhes serão acrescentadas." },
  { reference: "João 3:16", text: "Porque Deus tanto amou o mundo que deu o seu Filho unigênito, para que todo o que nele crer não pereça, mas tenha a vida eterna." },
  { reference: "Salmos 46:1", text: "Deus é o nosso refúgio e a nossa fortaleza, auxílio sempre presente na adversidade." },
  { reference: "Hebreus 11:1", text: "Ora, a fé é a certeza daquilo que esperamos e a prova das coisas que não vemos." },
  { reference: "Salmos 37:5", text: "Entregue o seu caminho ao Senhor; confie nele, e ele agirá." },
  { reference: "2 Coríntios 5:7", text: "Porque vivemos por fé, e não pelo que vemos." },
  { reference: "Josué 1:9", text: "Não fui eu que lhe ordenei? Seja forte e corajoso! Não se apavore nem desanime, pois o Senhor, o seu Deus, estará com você por onde você andar." },
  { reference: "Salmos 119:105", text: "A tua palavra é lâmpada que ilumina os meus passos e luz que clareia o meu caminho." },
  { reference: "Tiago 1:5", text: "Se algum de vocês tem falta de sabedoria, peça-a a Deus, que a todos dá livremente, de boa vontade; e lhe será concedida." },
  { reference: "Romanos 12:2", text: "Não se amoldem ao padrão deste mundo, mas transformem-se pela renovação da sua mente." },
  { reference: "Efésios 2:8", text: "Pois vocês são salvos pela graça, por meio da fé, e isto não vem de vocês, é dom de Deus." },
  { reference: "Salmos 121:1-2", text: "Elevo os meus olhos para os montes e pergunto: De onde me vem o socorro? O meu socorro vem do Senhor, que fez os céus e a terra." },
  { reference: "1 Pedro 5:7", text: "Lancem sobre ele toda a sua ansiedade, porque ele tem cuidado de vocês." },
  { reference: "Mateus 11:28", text: "Venham a mim, todos os que estão cansados e sobrecarregados, e eu lhes darei descanso." },
  { reference: "Gálatas 5:22-23", text: "Mas o fruto do Espírito é amor, alegria, paz, paciência, amabilidade, bondade, fidelidade, mansidão e domínio próprio." },
  { reference: "Romanos 15:13", text: "Que o Deus da esperança os encha de toda alegria e paz, por sua confiança nele." },
  { reference: "Colossenses 3:23", text: "Tudo o que fizerem, façam de todo o coração, como para o Senhor." },
  { reference: "Salmos 34:8", text: "Provem e vejam como o Senhor é bom." },
  { reference: "Lamentações 3:22-23", text: "As misericórdias do Senhor são a causa de não sermos consumidos, pois as suas misericórdias não têm fim; renovam-se cada manhã." },
  { reference: "1 Tessalonicenses 5:16-18", text: "Alegrem-se sempre. Orem continuamente. Deem graças em todas as circunstâncias." },
  { reference: "Isaías 40:31", text: "Mas aqueles que esperam no Senhor renovam as suas forças." },
  { reference: "Salmos 139:14", text: "Eu te louvo porque me fizeste de modo especial e admirável." },
  { reference: "João 14:6", text: "Eu sou o caminho, a verdade e a vida." },
  { reference: "Hebreus 13:8", text: "Jesus Cristo é o mesmo, ontem, hoje e para sempre." },
  { reference: "Romanos 6:23", text: "Pois o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna." },
  { reference: "Salmos 118:24", text: "Este é o dia em que o Senhor agiu; alegremo-nos e exultemos neste dia." },
  { reference: "Mateus 5:16", text: "Assim brilhe a luz de vocês diante dos homens." },
  { reference: "Provérbios 16:3", text: "Consagre ao Senhor tudo o que você faz, e os seus planos serão bem-sucedidos." },
  { reference: "2 Timóteo 1:7", text: "Pois Deus não nos deu espírito de covardia, mas de poder, de amor e de equilíbrio." },
  { reference: "Salmos 19:14", text: "Que as palavras da minha boca e a meditação do meu coração sejam agradáveis a ti." },
  { reference: "João 8:12", text: "Eu sou a luz do mundo." },
  { reference: "1 Coríntios 13:13", text: "Assim, permanecem agora estes três: a fé, a esperança e o amor. O maior deles, porém, é o amor." },
  { reference: "Efésios 6:10", text: "Finalmente, fortaleçam-se no Senhor e no seu forte poder." },
  { reference: "Salmos 91:1", text: "Aquele que habita no abrigo do Altíssimo descansará à sombra do Todo-poderoso." },
];
